server:
  port: 8080
  servlet:
    context-path: /
    
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/baseball?serverTimezone=Asia/Seoul
    username: baseball
    password: bitc5600
    driver-class-name: com.mysql.cj.jdbc.Driver 
